### ISSUE TITLE
Issue 1.9.1 - Group 2 Test Set 2.1-2.4

### ISSUE THREAD

**Issue by kokkenshodai** [CMPUT301W14T13/Team13GPSCommentLogger#22]
Create test set for Group 2 Use Cases.

**Comment by DevMomo** [comment]
@arweber1 is responsible for making tests for cases 2.1-2.4
I'm responsible for 2.5-2.8

**Comment by DevMomo** [comment]
We should have had separate issues for the responsibilities as specified in the email. We'll both comment to indicate completion before closing.
